/* WLLAMPLE.H */
#define IDM_ANALDATAFILE                101
#define IDM_DICTCODES                   102
#define IDM_DICTORTHOCHANGE             103
#define IDM_DICTIONARY                  104
#define IDM_TEXTCTL                     105
#define IDM_ANAFILE                     106
#define IDM_LOGFILE                     107
#define IDM_EXIT                        108
#define IDM_INPUTFILE                   111
#define IDM_DICTOUTFILE                 112
#define IDM_PROCESS                     201
#define IDM_ABOUT                       301
