call CreateGrammarTransform Templates templates
call CreateGrammarTransform AdjP adjp
call CreateGrammarTransform AdvP advp
call CreateGrammarTransform CP cp
call CreateGrammarTransform DP dp
call CreateGrammarTransform IP ip
call CreateGrammarTransform NP np
call CreateGrammarTransform PP pp
call CreateGrammarTransform QP qp
call CreateGrammarTransform VP vp
