call CreateWriterTransform IntroAndTypology intro
call CreateWriterTransform AdvP advp
call CreateWriterTransform AdjP adjp
call CreateWriterTransform NP np
call CreateWriterTransform N n
call CreateWriterTransform V v
call CreateWriterTransform Prop prop
call CreateWriterTransform Pron pron
call CreateWriterTransform PP pp
call CreateWriterTransform IP ip
call CreateWriterTransform Comp comp
call CreateWriterTransform Ques ques
call CreateWriterTransform RelCl relcl
call CreateWriterTransform AdvCl advcl
call CreateWriterTransform Neg neg
call CreateWriterTransform Coord coord
call CreateWriterTransform Focus focus
call CreateWriterTransform Excl excl
call CreateWriterTransform Appdx appdx