<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text" version="1.0" encoding="UTF-8" indent="yes"/>
  <!--
================================================================
Convert PAWS answers xml file to a PC-PATR grammar file
  Input:    xml file conforming to PAWSStarterKit.dtd
  Output: PC-PATR grammar file
================================================================
Revision History is at the end of this file.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Preamble
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-->
<xsl:param name="prmType">x</xsl:param>
  <!--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Main template
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-->
  <xsl:template match="/">
    <xsl:text>|
| **********************************************************************
| DO NOT EDIT THIS FILE UNTIL YOU HAVE COMPLETED THE ENTIRE STARTER KIT!
|
| (Otherwise your changes will get over-written the next time you save.)
| **********************************************************************
|
|PC-PATR Grammar file for PAWS Starter Kit
| C Black    July 2012
|
|------------------------------------------------------------------------------
|-Phrase structure rules
</xsl:text>
    <xsl:apply-templates select="/" mode="templates"/>
    <xsl:apply-templates select="/" mode="cp"/>
    <xsl:apply-templates select="/" mode="ip"/>
    <xsl:apply-templates select="/" mode="vpintcop"/>
    <xsl:apply-templates select="/" mode="vptran"/>
    <xsl:apply-templates select="/" mode="vpditranpp"/>
    <xsl:apply-templates select="/" mode="vpditrandp"/>
    <xsl:apply-templates select="/" mode="vpsentpass"/>
    <xsl:apply-templates select="/" mode="vppassvso"/>
    <xsl:apply-templates select="/" mode="vpvsoaux"/>
    <xsl:apply-templates select="/" mode="dp"/>
    <xsl:apply-templates select="/" mode="np"/>
    <xsl:apply-templates select="/" mode="pp"/>
    <xsl:apply-templates select="/" mode="adjp"/>
    <xsl:apply-templates select="/" mode="advp"/>
    <xsl:apply-templates select="/" mode="qp"/>
  </xsl:template>
    <!--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Include other templates
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-->
  <xsl:include href="GrammarTemplates.xsl"/>
  <xsl:include href="GrammarAdjP.xsl"/>
  <xsl:include href="GrammarAdvP.xsl"/>
  <xsl:include href="GrammarCP.xsl"/>
  <xsl:include href="GrammarDP.xsl"/>
  <xsl:include href="GrammarIP.xsl"/>
  <xsl:include href="GrammarNP.xsl"/>
  <xsl:include href="GrammarPP.xsl"/>
  <xsl:include href="GrammarQP.xsl"/>
  <xsl:include href="GrammarVPIntCop.xsl"/>
  <xsl:include href="GrammarVPTran.xsl"/>
  <xsl:include href="GrammarVPDitranPP.xsl"/>
  <xsl:include href="GrammarVPDitranDP.xsl"/>
  <xsl:include href="GrammarVPSentPass.xsl"/>
  <xsl:include href="GrammarVPPassVSO.xsl"/>
  <xsl:include href="GrammarVPVSOAux.xsl"/>
</xsl:stylesheet>
<!--
================================================================
Revision History
- - - - - - - - - - - - - - - - - - -
25-Feb-2011  Cheri Black Split VP file into parts
27-Oct-2004   Andy Black  Changed date to October 2004
31-Jul-2002    Andy Black  Changed name of generated transforms to Grammar*.xsl
18-Jul-2002    Andy Black  Reordered XSLs per Cheri's preference
17-Jul-2002    Andy Black  Added rest of XSLs
02-Jul-2002    Andy Black  Initial version
================================================================
 -->
