\_sh v3.0  400  text

\id ttintx.ctl text input control for Tlachichilco Tepehua 22 August 1994

\excl \id \_sh \h \g
\wfc á é í ú ó ' ñ

\ch "'" "†"
\ch "a" "†a" / #_
\ch "e" "†e" / #_
\ch "i" "†i" / #_
\ch "o" "†o" / #_
\ch "u" "†u" / #_
\ch "j" "h"
\ch "x" "š"
\ch "ts" "c"
\ch "ch" "©"
\ch "v" "w"
\ch "u" "w" / [V] _
\ch "lh" "£"
\ch "l" "£" / _ [C]
\ch "l" "£" / _ #
\ch "oo" "ow"
\ch "ke" "kiha" / #_ ~# | Problem: kijatapastak'ati vs. ket'alaqaunin, etc., not "ke"
\ch "me" "miha" /#_  | Problem: Spanish loans (mesa) and names (Melqui..)
