

	// CStudio.idl : IDL source for CStudio.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (CStudio.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(11EC31D6-094D-11D3-8664-88970CC10000),
		dual,
		helpstring("ICSHook Interface"),
		pointer_default(unique)
	]
	interface ICSHook : IDispatch
	{
	//	[id(1), helpstring("method LoadDefaults")] HRESULT LoadDefaults([in] VARIANT varICSTask);
		[id(2), helpstring("method PerformTask")] HRESULT PerformTask([in] VARIANT varICSTask);
		[propget, id(3), helpstring("property CurrentIntergenAnalysisMarkers")] HRESULT CurrentIntergenAnalysisMarkers([in] BSTR bstrLangCode, [out, retval] BSTR *pAnalysisMarkers);
		[propget, id(4), helpstring("property LangCodes")] HRESULT LangCodes([out, retval] VARIANT *pVal);
		[propget, id(5), helpstring("property LangCodesString")] HRESULT LangCodesString([out, retval] BSTR *pVal);
		[propget, id(6), helpstring("property CurrentIntergenWordMarker")] HRESULT CurrentIntergenWordMarker([in] BSTR bstrLangCode, [out, retval] BSTR *pWordMarker);
		[propget, id(7), helpstring("property CurrentTextInIncludeExcludeMarkers")] HRESULT CurrentTextInIncludeExcludeMarkers([in] BSTR bstrLang, [out, retval] BSTR *pVal);
		[propget, id(8), helpstring("property CurrentTextInIncludeSpecified")] HRESULT CurrentTextInIncludeSpecified([in]BSTR bstrLang, [out, retval] BOOL *pVal);
	};
	[
		object,
		uuid(6698ECD9-76C3-48C7-939E-BD39BFE27455),
		dual,
		helpstring("IParseCS Interface"),
		pointer_default(unique)
	]
	interface IParseCS : IDispatch
	{
		[id(1), helpstring("method ParseString")] HRESULT ParseString([in]BSTR bstrPhrase, [in] BOOL bTrace, [in] BSTR bstrTraceWords, [in] BOOL bForceRefresh, [out, retval] BSTR *pbstrResult);
		[propget, id(2), helpstring("property Options")] HRESULT Options([out, retval] long *pVal);
		[propput, id(2), helpstring("property Options")] HRESULT Options([in] long newVal);
		[propget, id(3), helpstring("property LangCodesString")] HRESULT LangCodesString([out, retval] BSTR *pVal);
		[propget, id(4), helpstring("property SourceLangeCode")] HRESULT SourceLangeCode([out, retval] BSTR *pVal);
		[propput, id(4), helpstring("property SourceLangeCode")] HRESULT SourceLangeCode([in] BSTR newVal);
		[id(5), helpstring("method ParseFile")] HRESULT ParseFile(BSTR sInputFilePath, BSTR sOutputFilePath, BOOL bForceRefresh);
		[propget, id(6), helpstring("property LangInfoXML")] HRESULT LangInfoXML([out, retval] BSTR *pVal);
	};



[
	uuid(11EC31D4-094D-11D3-8664-88970CC10000),
	version(1.0),
	helpstring("CStudio 1.0 Type Library")
]
library CStudioLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	[
		uuid(11EC31D7-094D-11D3-8664-88970CC10000),
		helpstring("CSHook Class")
	]
	coclass CSHook
	{
		[default] interface ICSHook;
	};

	[
		uuid(5A2AFAD2-B372-4F91-AD5D-23905E202EE3),
		helpstring("ParseCS Class")
	]
	coclass ParseCS
	{
		[default] interface IParseCS;
	};
};
