//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CStudio.rc
//
#define IDS_WizCatProp_RPS_ST           1
#define IDtest                          3
#define IDD_ABOUTBOX                    100
#define IDR_CSTUDIO                     101
#define CG_IDD_PROGRESS                 102
#define CG_IDS_PROGRESS_CAPTION         103
#define IDD_ProcessSettings             104
#define IDS_CONT_PROC_FAILURE           104
#define IDD_Categories                  105
#define IDS_CONT_PROC_FAILURE2          105
#define IDD_PageLangDisplayProperties   106
#define IDS_NewFromScratchCaption       107
#define IDS_WizCatProp_RPS_FT           108
#define IDS_WizCatProp_RSP_FT           109
#define IDS_WizCatProp_RSP_RT           110
#define IDS_WizFinalCat_RSP_FT          111
#define IDS_WizCatProp_Pfx_InsideOut_PT 112
#define IDS_WizCatProp_Sfx_InsideOut_ST 113
#define IDS_WizFinalCatClassField       114
#define IDB_LIGHTBULB                   115
#define IDD_TIP                         116
#define CG_IDS_TIPOFTHEDAY              117
#define CG_IDS_TIPOFTHEDAYMENU          118
#define CG_IDS_DIDYOUKNOW               119
#define CG_IDS_FILE_ABSENT              120
#define CG_IDP_FILE_CORRUPT             121
#define CG_IDS_TIPOFTHEDAYHELP          122
#define IDS_WizOrderclass_A0_ST         123
#define IDS_WizOrderclass_A0_FT         124
#define IDS_WizCatProp_Ifx_InsideOut_ST 125
#define IDS_WizBuiltIn_MCC_FT           126
#define IDS_WizBuiltIn_SEC_ST           127
#define IDR_MAINFRAME                   128
#define IDR_CStudioPTYPE                129
#define IDS_COLUMN1                     130
#define IDS_COLUMN2                     131
#define IDS_FilesWizCaption             132
#define IDS_SetupWizCaption             133
#define IDD_HEADING_VIEW                134
#define IDS_MUST_BE_ANSI                134
#define IDR_CStudioLangTYPE             135
#define IDR_CStudioAnaDocType           136
#define IDR_CStudioSrcDocType           137
#define IDR_CLogWindowType              138
#define IDR_QuickParseDocType           139
#define IDD_WizFilesTransfer            140
#define IDD_WizFilesSynth               141
#define IDS_WizBuiltIn_ROOTS_ST         142
#define IDD_WizFilesFinish              143
#define IDD_WizSetupTests               144
#define IDD_WizSetupOrderclass          145
#define IDD_WizSetupFinish              146
#define IDR_CONNECTOR                   147
#define IDI_EnabledListItem             148
#define IDI_DisabledListItem            149
#define IDI_EnabledEnvItem              150
#define IDI_DisabledEnvItem             151
#define IDD_EditEnvironment             152
#define IDD_EditMCC                     153
#define IDI_Process                     154
#define IDD_ProcessSequence             155
#define IDD_QuickParse                  156
#define IDD_EditClass                   157
#define IDD_EditAdhocPair               158
#define IDD_EditCompoundRoot            159
#define IDS_WizCatProp_RSP_ST           160
#define IDS_LanguageFileType            161
#define IDR_CStudioTYPE                 162
#define IDD_EditAmpleProcess            163
#define IDD_EditIntergenProcess         164
#define IDD_EditJoinCompProcess         165
#define IDD_ProcessStatus               166
#define IDD_WizProjectLocation          167
#define IDD_WizCMenuSettings            168
#define IDD_ChooseProcessor             169
#define IDD_PageFilesDict1              170
#define IDD_PageCatFinalTest            171
#define IDS_Filter_Dictionary           172
#define IDS_TTAddFile                   173
#define IDS_Credits                     174
#define IDR_LangPopup                   175
#define IDS_UNUSEDWizCatProp_RPS_FT     176
#define IDS_WizFinalCat_RPS_FT          177
#define IDD_EditSentransDisambig        178
#define IDR_InputDocPopup               179
#define IDD_EditSentransTransfer        180
#define IDD_PageSrcTextProcessing       181
#define IDD_EditSentransDirective       182
#define IDD_EditSentransProcess         183
#define IDD_EditStampTransferRule       184
#define IDD_EditStampFlag               185
#define IDD_EditStampLexChange          186
#define IDD_EditRegularSoundChange      187
#define IDD_EditStampProcess            188
#define IDD_LanguageCreation            189
#define IDD_Environments                190
#define IDD_PageInputDocPanels          191
#define IDI_NOT                         192
#define IDD_EditPhonruleRule            193
#define IDD_PageRedundantFieldNotice    194
#define IDD_CCProcess                   195
#define IDD_PageAnaProcessing           196
#define IDD_EditTest                    197
#define IDD_ProjectSettings             198
#define IDD_OpenOrCreateProject         199
#define IDD_WizFilesAnalysis            200
#define IDB_Construction                201
#define IDD_PageAffixes                 202
#define IDD_PageCatPropogation          203
#define IDI_Construction                204
#define IDD_PageDictAffix               205
#define IDD_ChooseDictMethod            206
#define IDD_PageLocations               207
#define IDD_PageDisclaimer              208
#define IDD_EditAmpleDLLProcess         209
#define IDS_WizOrderclass_A0_PT         210
#define IDC_CURSOR1                     211
#define IDS_WizOrderclass_A0_IT         211
#define IDB_Delete                      212
#define IDB_AddFile                     213
#define IDB_SPLASH                      214
#define IDB_ChooseFolder                215
#define IDB_Environment                 216
#define IDI_MorphEnvironment            217
#define IDI_DisabledOverlay             218
#define IDI_StringEnvironment           219
#define IDR_EnvironPopup                220
#define IDI_GenericListItem0            221
#define IDI_GenericListItem1            222
#define IDI_UNUSEDERROR                 223
#define IDI_SFMarker                    224
#define IDI_Editable                    225
#define IDR_QuickParseDocType1          226
#define IDI_STAMPFlag                   227
#define IDS_NewFromCarlaWizCaption      228
#define IDS_WizBuiltIn_MEC_FT           229
#define IDS_WizBuiltIn_ADHOC_ST         230
#define IDI_GenericListItem2            231
#define IDI_SENTRANSLimit               232
#define IDI_SENTRANSBegin               233
#define IDI_SENTRANSEnd                 234
#define IDI_SENTRANSRulesOn             235
#define IDI_SENTRANSRulesOff            236
#define IDD_PageDictRootUnified         237
#define IDS_SelectFolderPrompt          238
#define IDB_Error                       239
#define IDR_HOOK                        240
#define IDS_MSGCancelMeansDefault       241
#define IDD_EditToneParseProcess        242
#define IDI_CommentListItem             243
#define IDD_EditComment                 244
#define IDD_ModifyTestsFinish           245
#define IDS_MSGCompoundRootsNeedTwoCats 246
#define IDS_WizCatProp_RPS_RT           247
#define IDS_ModifyTestsAffixPage        248
#define IDS_ModifyTestsCatPropPage      249
#define IDS_WizCatProp_RS_ST            250
#define IDS_WizFinalCat_RS_FT           251
#define IDD_EditOrthoChange             252
#define IDS_ModifyTestsFinalCatTests    252
#define IDD_EditTestData                253
#define IDI_TestDataListItem            254
#define IDD_EditPrintANAProcess         255
#define IDD_BatchProcess                256
#define IDD_ManualParseChoice           257
#define IDR_PARSECS                     258
#define IDD_EditToneGenProcess          259
#define IDD_EditToneTracing             260
#define IDD_PageCatFinalModifyTest      261
#define IDI_LOADING_1                   261
#define IDI_LOADING_2                   262
#define IDB_SPLASHU                     262
#define IDI_LOADING_3                   263
#define IDI_ERR_LOADING_1               264
#define IDI_ERR_LOADING_2               265
#define IDI_ERR_LOADING_3               266
#define IDC_EDIT1                       1000
#define IDC_EDITRuleFile                1000
#define IDC_EDITTraceLevelParse         1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTONToneGenControlFile    1001
#define IDC_BUTTONToneParsControlFile   1001
#define IDC_BUTTONPhonrule              1002
#define IDC_LIST1                       1003
#define IDC_LIST_AMPLE_ALLOS            1003
#define IDC_RADIO1                      1004
#define IDC_RADIOBatchFileKind          1004
#define IDC_RADIO2                      1005
#define IDC_BUTTON2                     1006
#define IDC_BUTTONToneGenTraceOptions   1006
#define IDC_BUTTONToneParsTraceOptions  1006
#define IDC_BUTTONVernFont              1007
#define IDC_BUTTONSTDisam               1008
#define IDC_FontDescription             1009
#define IDC_STATICTextIn                1010
#define IDC_STATICCmd                   1011
#define IDC_STATICPhonrule              1012
#define IDC_STATICSrcOrtho              1013
#define IDC_STATICSrcCodeTable          1014
#define IDC_STATICAnalysis              1015
#define IDC_STATICSTDisam               1016
#define IDC_BUTTONStXfer                1017
#define IDC_STATICSTXfer                1018
#define IDC_BUTTONStampXfer             1019
#define IDC_STATICStampXfer             1020
#define IDC_BUTTONTargCodeTable         1021
#define IDC_STATICTargCodeTable         1022
#define IDC_BUTTONTAMPSynth             1023
#define IDC_STATICSTAMPSynth            1024
#define IDC_BUTTONTargOrtho             1025
#define IDC_STATICTargOrtho             1026
#define IDC_Root2                       1027
#define IDC_STATICTargTextOut           1028
#define IDC_CHECK4                      1029
#define IDC_CHECKToneTraceTBU           1029
#define IDC_CHECKToneGenOutputAll       1029
#define IDC_CHECKDisplayAnalysesOnly    1030
#define IDC_CHECK2                      1031
#define IDC_CHECKToneTraceMora          1031
#define IDC_CHECKToneGenMoprhnames      1031
#define IDC_CHECKToneGenMorphnames      1031
#define IDC_STATICMsg                   1032
#define IDC_To                          1033
#define IDC_Comments                    1034
#define IDC_CHECKEnabled                1035
#define IDC_From                        1036
#define IDC_Environment                 1037
#define IDC_EnvironComment              1038
#define IDC_Members                     1039
#define IDC_TABBar                      1040
#define IDC_InsertAfter                 1041
#define IDC_CheckRootCats               1042
#define IDC_Trace                       1043
#define IDC_AllomorphMarker             1044
#define IDC_RADIOInsert                 1045
#define IDC_CHECKShowDOSBox             1046
#define IDC_ItxTest                     1047
#define IDC_Cat1                        1048
#define IDC_Cat2                        1049
#define IDC_Morph1                      1050
#define IDC_Morph2                      1051
#define IDC_EDITComments                1052
#define IDC_COMBOMorphTypes             1053
#define IDC_Properties                  1054
#define IDC_InsertBefore                1055
#define IDC_Remove                      1056
#define IDC_CheckMorphnames             1057
#define IDC_MonitorProgress             1058
#define IDC_OutputRootGlosses           1059
#define IDC_ParseTrees                  1060
#define IDC_MaxMorphLength              1061
#define IDC_DecompChar                  1062
#define IDC_UseSFMarkers                1063
#define IDC_MaxLineLength               1064
#define IDC_IncludeOriginalWord         1065
#define IDC_IncludeFeature              1066
#define IDC_IncludeCategory             1067
#define IDC_PartialCompoundsOK          1068
#define IDC_VariantFormMarker           1069
#define IDC_JoinWordsMarker             1070
#define IDC_CopyDicts                   1071
#define IDC_TIPSTRING                   1072
#define IDC_ProgressEdit                1073
#define IDC_BTNProjectLoc               1074
#define IDC_ProjectLoc                  1075
#define IDC_CarlaSetPath                1076
#define IDC_BTNCarlaSetPath             1077
#define IDC_CUSTOM1                     1078
#define IDC_SourceLang                  1079
#define IDC_TargetLangCombo             1080
#define IDC_MakeDefault                 1081
#define IDC_Morphemes                   1082
#define IDC_RADIOAccept                 1083
#define IDC_RADIOReject                 1084
#define IDC_radioAnalysisOnly           1085
#define IDC_radioGlossing               1086
#define IDC_radioAutoSynthesis          1087
#define IDC_radioAnalyzeTransfer        1088
#define IDC_bSynthesize                 1089
#define IDC_MonitorAmibiguities         1090
#define IDC_MonitorRulesApplied         1091
#define IDC_TraceRules                  1092
#define IDC_OutputClassContents         1093
#define IDC_RADIOType5                  1094
#define IDC_RADIOProduce                1095
#define IDC_radioFunction1              1096
#define IDC_radioFunction2              1097
#define IDC_radioFunction3              1098
#define IDC_RADIOCopy                   1099
#define IDC_radioFunction5              1099
#define IDC_RADIOSubstitute             1100
#define IDC_sMorphemes                  1101
#define IDC_sComments                   1102
#define IDC_sFlag                       1103
#define IDC_radioFunction4              1104
#define IDC_OutputAllAllomorphs         1105
#define IDC_Verbose                     1106
#define IDC_StaticCopyNotice            1107
#define IDC_btnTextOut                  1108
#define IDC_RADIOType4                  1109
#define IDC_btnSTAMPSynth               1110
#define IDC_EDITTraceMorphs             1111
#define IDC_TextOut                     1112
#define IDC_STAMPSynth                  1113
#define IDC_STATICDictOrtho             1114
#define IDC_BUTTONDictOrtho             1115
#define IDC_BUTTONCodeTable             1116
#define IDC_STATICCodeTable             1117
#define IDC_MSFLEXGRID1                 1118
#define IDC_ValidMsg                    1119
#define IDC_PanelDetails                1120
#define IDC_availableOnly               1121
#define IDC_iLimit                      1122
#define IDC_FolderPath                  1123
#define IDC_CHECKTrace                  1124
#define IDC_EDITInput                   1125
#define IDC_EDITSeconds                 1126
#define IDC_RADIORuleType               1127
#define IDC_RADIOBaseRule               1128
#define IDC_RADIOForce                  1129
#define IDC_RADIOInitial                1130
#define IDC_RADIOFinal                  1131
#define IDC_RADIOType3                  1132
#define IDC_InputLang                   1133
#define IDC_RADIOType2                  1134
#define IDC_STATICTablePath             1135
#define IDC_BULB                        1136
#define IDC_commentChar                 1137
#define IDC_EDITEXEName                 1138
#define IDC_SComment                    1139
#define IDC_BUTTONTextIn                1140
#define IDC_STARTUP                     1141
#define IDC_BUTTONBrowseTableFile       1142
#define IDC_BtnAddRoot                  1143
#define IDC_EDITControlFile             1144
#define IDC_EDITAnswerFile              1145
#define IDC_EDITAmpleOutput             1146
#define IDC_NEXTTIP                     1147
#define IDC_BtnRemove                   1148
#define IDC_EDITTraceLevel              1149
#define IDC_BUTTONSrcOrtho              1150
#define IDC_EDIT3                       1151
#define IDC_ProcessList                 1152
#define IDC_LIST                        1153
#define CG_IDC_PROGDLG_PROGRESS         1154
#define IDC_InputDocPanelList           1155
#define IDC_BUTTONCmd                   1156
#define IDC_FieldList                   1157
#define IDC_RootDicts                   1158
#define IDC_EnvList                     1159
#define IDC_BUTTONSrcCodeTable          1160
#define CG_IDC_PROGDLG_PERCENT          1161
#define IDC_BUTTONAnalysis              1162
#define CG_IDC_PROGDLG_STATUS           1163
#define IDC_RControlFiles               1164
#define IDC_RADIO3                      1165
#define IDC_RADIO4                      1166
#define IDC_RADIOFileKind               1167
#define IDC_RADIO5                      1168
#define IDC_EDITLabel                   1169
#define IDC_EDITDescription             1170
#define IDC_EDITContents                1171
#define IDC_RProjectWizard              1172
#define IDC_RCarlaMenu                  1173
#define IDC_Dict1Path                   1174
#define IDC_Root1                       1175
#define IDC_BUTTONDict1                 1176
#define IDC_BTNRoot1                    1177
#define IDC_BTNPrefix                   1178
#define IDC_EDITFilesList               1179
#define IDC_Prefix                      1180
#define IDC_BUTTONSTDisambig            1181
#define IDC_EDITAbrev                   1182
#define IDC_BTNInfix                    1183
#define IDC_STDisambig                  1184
#define IDC_EDITName                    1185
#define IDC_Infix                       1186
#define IDC_StaticFont                  1187
#define IDC_BTNSuffix                   1188
#define IDC_STGlossing                  1189
#define IDC_BUTTONFont                  1190
#define IDC_Suffix                      1191
#define IDC_CHECKFinalCat               1192
#define IDC_BTNRoot2                    1193
#define IDC_BUTTONTargTextOut           1194
#define IDC_CHECK3                      1195
#define IDC_CHECKToneTraceSyllable      1195
#define IDC_CHECKToneGenRootCats        1195
#define IDC_BTNRoot3                    1196
#define IDC_bDisplaySegmentInventory    1197
#define IDC_Root3                       1198
#define IDC_BTNRoot4                    1199
#define IDC_CHECKSfx                    1200
#define IDC_allDecompAmbiguities        1201
#define IDC_bMonitorProgress            1202
#define IDC_ShowFromTransfer            1203
#define IDC_Root4                       1204
#define IDC_bTraceToneProcessing        1205
#define IDC_ReportAmbig                 1206
#define IDC_IncludeDecomp               1207
#define IDC_BTNRoot5                    1208
#define IDC_CHECKIfx                    1209
#define IDC_WriteDecompField            1210
#define IDC_IncludeAnalysis             1211
#define IDC_Root5                       1212
#define IDC_WritePField                 1213
#define IDC_IncludeUForm                1214
#define IDC_WriteWordField              1215
#define IDC_IncludeProperty             1216
#define IDC_Category                    1217
#define IDC_radioGoal                   1218
#define IDC_radioAnalyzeTransfer2       1219
#define IDC_CHECKUnanimousEnvirons      1220
#define IDC_RADIOType                   1221
#define IDC_btnSTGlossing               1222
#define IDC_StaticSameDirNotice         1223
#define IDC_RSCIds                      1224
#define IDC_STestData                   1225
#define IDC_btnStampDictCode            1226
#define IDC_StampDictCode               1227
#define IDC_BUTTONCodeTableIt           1228
#define IDC_STATICCodeTableIt           1229
#define IDC_bVerifyControlFileInformation 1230
#define IDC_bMonitorProgressGen         1231
#define IDC_bDisplaySegmentInventoryGen 1232
#define IDC_bVerifyControlFileInformationGen 1233
#define IDC_bTraceToneProcessingGen     1234
#define IDC_EDITTraceLevelGen           1235
#define IDC_EDITEXENameGen              1236
#define IDC_EDITControlFileGen          1237
#define IDC_EDITAnswerFileGen           1238
#define IDC_STATICWordToParse           3000
#define IDC_RADIOx                      3001
#define IDC_DictMethod2                 3002
#define IDC_TransferedANA               3003
#define IDC_Synthesized                 3004
#define IDC_Credits                     3005
#define IDC_CHECKPfx                    3006
#define IDC_CHECKDisableFinalCat        3007
#define IDC_CHECKCreateFinalCatTest     3008
#define IDC_CatPropScheme               3009
#define IDC_RADIOSfx                    3010
#define IDC_DictMethod                  3011
#define IDC_BtnDictMethod               3012
#define IDC_DictListLabel               3013
#define IDC_AnalyzedANA                 3014
#define IDC_Interlinear                 3015
#define IDC_MorphnamesInLangFont        3016
#define IDC_CommentsInLangFont          3017
#define IDC_CopyInterlinearToSrcDir     3018
#define IDC_FromOrInsert                3019
#define IDC_FromOrInsertLabel           3020
#define IDC_ToStatic                    3021
#define IDC_Flags                       3022
#define IDC_FromOrInsertLabel2          3023
#define IDC_LeaveNonGoalsInTemp         3024
#define IDC_ErrorIcon                   3025
#define IDC_ErrorStatic                 3026
#define IDC_ErrorStatic2                3027
#define IDC_RADIOProduceTANA            3028
#define IDC_TestContentsInLangFont      3029
#define IDC_StringClassInLangFont       3030
#define IDC_MorphemeClassInLangFont     3031
#define IDC_DisableFontAssociation      3032
#define IDC_PropertiesInLangFont        3033
#define IDC_EDITEXENamePrintAna         3034
#define IDC_EDITBeginPrintColumn        3035
#define IDC_STATICBatchPath             3036
#define IDC_BUTTONBrowseBatchFile       3037
#define IDC_RefreshNotice               3038
#define IDC_CHECK_IntergenOutputChanges 3039
#define IDC_CHECKManualParse            3040
#define IDC_STATICManualParse           3041
#define IDC_LISTManualParse             3042
#define IDC_CHECKToneTraceSegments      3043
#define IDC_CHECKToneTraceLinkAnalysis  3044
#define IDC_CHECKToneTraceToneRule      3045
#define IDC_CHECKToneTraceDomains       3046
#define IDC_CHECKToneTraceTierAssignment 3047
#define IDC_CHECKToneTraceMorphemeTone  3048
#define IDC_CHECKToneGenTraceSynthesis  3049
#define IDC_CHECKToneParseMorphnames    3050
#define IDC_CHECKCreateFinalCatTestModifyTests 3051
#define IDC_CHECKDisableFinalCatModifyTests 3052
#define IDC_STATICcomments              3054
#define IDC_STATICcategory              3055
#define IDC_STATICto                    3056
#define IDC_STATICapply                 3057
#define IDC_Uncheck                     3058
#define IDLangSetup                     32771
#define ID_FILE                         32772
#define IDProjectSetup                  32773
#define ID_RunProcessors                32774
#define ID_CARLAMenu                    32775
#define ID_AmpleLinks                   32776
#define ID_Edit_Insert                  32777
#define ID_EDIT_insert_environ          32778
#define ID_Edit_Insert_Entry            32779
#define ID_Edit_Delete                  32780
#define ID_EditInputDocProperties       32781
#define ID_FILE_SaveAll                 32782
#define ID_FILE_SAVEProject             32783
#define IDS_ProcessSeqProgressCaption   32784
#define ID_edit_insert_secondary        32785
#define ID_FILE_NewLanguage             32786
#define ID_FILE_NEW_PROJECT             32787
#define ID_NULL                         32788
#define ID_LangProperties               32789
#define ID_LangAnalysisSeq              32790
#define ID_LangSynthesisSeq             32791
#define ID_InputDocDisplay              32792
#define ID_FILE_OPEN_Project            32793
#define ID_FILE_OPEN_Document           32794
#define ID_FILE_CLOSE_PROJECT           32795
#define ID_FILE_MRU_PROJECT             32796
#define ID_FILE_PROJECTS                32802
#define ID_LangQuickParse               32803
#define ID_BUTTON32827                  32804
#define ID_LangInterlinearSeq           32805
#define ID_EDIT_Edit                    32806
#define ID_EDIT_Properties              32807
#define ID_OpenStream                   32808
#define ID_OpenStreamExternal           32809
#define ID_QuickParse_ChangeLang        32810
#define ID_QuickParseGo                 32811
#define ID_POPUP_DISABLE                32812
#define ID_Enable_Item                  32813
#define ID_Env_Delete                   32814
#define ID_Env_Enable                   32815
#define ID_FILE_NewDocument             32816
#define ID_FILE_SAVEDOCUMENTAS          32817
#define ID_Jump                         32818
#define ID_EDIT_FindAgain               32819
#define ID_EDIT_Insert_Comment          32820
#define ID_POPUP_PROCESSPROPERTIES      32821
#define ID_LANGUAGE_REMOVETHELANGUAGE   32822
#define ID_LangRemove                   32823
#define ID_LANGUAGE_SETUPTESTS          32824
#define ID_btnTrace                     32825
#define ID_ToggleTrace                  32826
#define ID_Trace                        32827
#define ID_RunTrace                     32828
#define ID_EDIT_Insert_TestData         32829
#define ID_QUICKPARSE_RefreshRequest    32830

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        267
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         3059
#define _APS_NEXT_SYMED_VALUE           148
#endif
#endif
