//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamplesFromANA.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamplesFromANA.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Icon CStudio {
			get {
				object obj = ResourceManager.GetObject("CStudio", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
		///
		///&lt;!--
		///   Merging two XML files
		///   Version 1.6
		///   LGPL (c) Oliver Becker, 2002-07-05
		///   obecker@informatik.hu-berlin.de
		///--&gt;
		///
		///&lt;xslt:transform version=&quot;1.0&quot;
		///                xmlns:xslt=&quot;http://www.w3.org/1999/XSL/Transform&quot;
		///                xmlns:m=&quot;http://informatik.hu-berlin.de/merge&quot;
		///                exclude-result-prefixes=&quot;m&quot;&gt;
		///
		///
		///&lt;!-- Normalize the contents of text, comment, and processing-instruction
		///     nodes before comparing?
		///     Default: yes --&gt;
		///&lt;xslt:param name=&quot;normalize&quot; select= [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string merge {
			get {
				return ResourceManager.GetString("merge", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to \_sh v3.0  400  CarlaStudioANA
		///
		///.
		/// </summary>
		internal static string ToolboxSFMHeader {
			get {
				return ResourceManager.GetString("ToolboxSFMHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&amp;gt;.
		/// </summary>
		internal static string XmlFileHeader {
			get {
				return ResourceManager.GetString("XmlFileHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;merge xmlns=&quot;http://informatik.hu-berlin.de/merge&quot;&gt;
		///  &lt;file1&gt;{0}&lt;/file1&gt;
		///  &lt;file2&gt;{1}&lt;/file2&gt;
		///&lt;/merge&gt;
		///.
		/// </summary>
		internal static string XSLTMergeInput {
			get {
				return ResourceManager.GetString("XSLTMergeInput", resourceCulture);
			}
		}
	}
}
